from django.db import models


class Department(models.Model):
    DEPARTMENT_TYPES = [
        ("ACC", "Accident & Emergency"),
        ("ADM", "Administration"),
        ("ALL", "Allergy & Immunology"),
        ("AMB", "Ambulance Services"),
        ("ANA", "Anesthesiology"),
        ("AUD", "Audiology"),
        ("BEH", "Behavioral Health"),
        ("BIO", "Biochemistry"),
        ("BLD", "Blood Bank"),
        ("BMT", "Bone Marrow Transplant"),
        ("BRN", "Breast Cancer"),
        ("CAR", "Cardiac Rehabilitation"),
        ("CHM", "Chemotherapy"),
        ("CLN", "Clinical Services"),
        ("CRD", "Cardiology"),
        ("CRT", "Cardiac Surgery"),
        ("DEN", "Dentistry"),
        ("DER", "Dermatology"),
        ("DIA", "Diabetic Care"),
        ("DIE", "Dietetics"),
        ("DVA", "Diagnostic Imaging"),
        ("EAR", "Ear, Nose & Throat"),
        ("ECG", "Electrocardiography"),
        ("EMR", "Emergency Medicine"),
        ("EMT", "Emergency Medical Technicians"),
        ("END", "Endocrinology"),
        ("EPL", "Epilepsy"),
        ("FER", "Fertility Services"),
        ("GAS", "Gastroenterology"),
        ("GEN", "General Practice"),
        ("GER", "Geriatrics"),
        ("GYN", "Gynecology"),
        ("HEM", "Hematology"),
        ("HEP", "Hepatology"),
        ("HOS", "Hospice Care"),
        ("HPV", "Human Papillomavirus"),
        ("HRM", "Human Resources Management"),
        ("ICU", "Intensive Care Unit"),
        ("IFD", "Infectious Diseases"),
        ("INF", "Infertility Services"),
        ("INR", "Inpatient Rehabilitation"),
        ("INT", "Internal Medicine"),
        ("IVF", "In Vitro Fertilization"),
        ("LAB", "Laboratory Services"),
        ("LTC", "Long-Term Care"),
        ("LYM", "Lymphology"),
        ("MAM", "Mammography"),
        ("MED", "Medical Records"),
        ("MEN", "Mental Health"),
        ("MTN", "Maternity Services"),
        ("NEO", "Neonatology"),
        ("NEP", "Nephrology"),
        ("NEU", "Neurology"),
        ("NTR", "Nutrition Services"),
        ("NUC", "Nuclear Medicine"),
        ("OBG", "Obstetrics & Gynecology"),
        ("ONC", "Oncology"),
        ("ONR", "Oncology Radiotherapy"),
        ("OPH", "Ophthalmology"),
        ("OPT", "Optometry"),
        ("ORT", "Orthopedics"),
        ("OST", "Osteopathy"),
        ("OTH", "Otolaryngology"),
        ("OTO", "Otology"),
        ("OXY", "Oxygen Therapy"),
        ("PAL", "Palliative Care"),
        ("PAR", "Paramedics"),
        ("PAT", "Pathology"),
        ("PDE", "Pediatric Dentistry"),
        ("PED", "Pediatrics"),
        ("PHM", "Pharmaceutical Services"),
        ("PHY", "Physiotherapy"),
        ("PLN", "Planning & Management"),
        ("PLT", "Plastic Surgery"),
        ("PMR", "Physical Medicine & Rehabilitation"),
        ("POD", "Podiatry"),
        ("PRE", "Preventive Medicine"),
        ("PRM", "Premises Management"),
        ("PSY", "Psychiatry"),
        ("PSYA", "Psychiatric Assessment"),
        ("PSYC", "Psychiatric Counseling"),
        ("PSYT", "Psychiatric Therapy"),
        ("PTH", "Pathology"),
        ("PUL", "Pulmonology"),
        ("RAD", "Radiology"),
        ("RDT", "Radiotherapy"),
        ("REN", "Renal Care"),
        ("RES", "Respiratory Care"),
        ("RHB", "Rehabilitation Services"),
        ("RHM", "Rheumatology"),
        ("SLP", "Speech-Language Pathology"),
        ("SOC", "Social Services"),
        ("SPI", "Spinal Cord Injury"),
        ("SPM", "Sports Medicine"),
        ("SUR", "Surgery"),
        ("THR", "Therapeutic Radiology"),
        ("TRA", "Transplant Services"),
        ("TRU", "Trauma Services"),
        ("URO", "Urology"),
        ("VAS", "Vascular Surgery"),
        ("VIR", "Virology"),
        ("WMN", "Women's Health"),
        ("WND", "Wound Care"),
    ]
    department_name = models.CharField(
        blank=False, null=False, max_length=100, default=""
    )
    department_type = models.CharField(
        choices=DEPARTMENT_TYPES, max_length=50, blank=False, null=False, default=""
    )
    department_id = models.CharField(
        max_length=20, blank=False, null=False, default="CRD-001"
    )
    department_contact_number = models.CharField(
        max_length=100, blank=True, null=True, default="07795128311"
    )

    def get_department_type_display(self):
        return dict(Department.DEPARTMENT_TYPES)[self.department_type]

    def __str__(self):
        return self.get_department_type_display()
