# Generated by Django 5.0.3 on 2024-03-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BINA_departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_contact_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
