# Generated by Django 5.0.3 on 2024-03-20 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=100)),
                ('ods_code', models.CharField(max_length=25, unique=True)),
                ('organisation_logo', models.ImageField(blank=True, null=True, upload_to='organisation_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name_or_number', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('town_or_city', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='BINA_organisations.organisation')),
            ],
        ),
    ]
