# Generated by Django 5.0.3 on 2024-03-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BINA_organisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationaddress',
            name='county',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
