# Generated by Django 5.0.3 on 2024-03-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BINA_organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='organisation_logo',
            field=models.ImageField(blank=True, null=True, upload_to='organisation_logos/'),
        ),
    ]
