# Generated by Django 5.0.3 on 2024-03-22 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BINA_departments', '0001_initial'),
        ('BINA_organisations', '0001_initial'),
        ('BINA_roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('other_names', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('contact_number', models.CharField(default='', max_length=30)),
                ('work_email', models.EmailField(default='', max_length=100)),
                ('ods_code', models.CharField(default='AA66TY', max_length=20)),
                ('specialises_in', models.CharField(default='', max_length=100)),
                ('access_level', models.CharField(choices=[('S', 'Symptoms'), ('RD', 'Real-Time Data'), ('HI', 'Health Information'), ('RED', 'Recorded Health Data'), ('L1B', 'Level 1 - Basic'), ('L2G', 'Level 2 - General'), ('L3D', 'Level 3 - Detailed'), ('XNA', 'No Access'), ('MA88', 'Master Access')], default='', max_length=10)),
                ('bina_q_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('temp_password_used', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BINA_departments.department')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BINA_organisations.organisation')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BINA_roles.role')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='healthcare_worker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthcareWorkerPersonalNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note_urgency', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=12)),
                ('healthcare_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='BINA_healthcare_workers.healthcareworker')),
            ],
        ),
    ]
