# Generated by Django 5.0.3 on 2024-03-18 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BINA_healthcare_workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareWorkerPersonalNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('healthcare_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='BINA_healthcare_workers.healthcareworker')),
            ],
        ),
    ]
