# Generated by Django 5.0.3 on 2024-03-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BINA_healthcare_workers', '0002_healthcareworkerpersonalnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcareworkerpersonalnotes',
            name='note_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
