# Generated by Django 5.0.3 on 2024-03-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BINA_healthcare_workers', '0004_healthcareworkerpersonalnotes_note_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcareworkerpersonalnotes',
            name='note_text',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
